apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: dev
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: scottazurecontainerregistry.azurecr.io/ecommerce-mysql:latest
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: connectionString