apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice-deployment
  namespace: dev
  labels:
    app: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
        - name: products-microservice
          image: microecommerceregistry.azurecr.io/products-microservice:__TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: ecommerceproductsdatabase
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin
            - name: ConnectionStrings__DefaultConnection
              value: "Server=$(MYSQL_HOST);Port=$(MYSQL_PORT);Database=$(MYSQL_DB);UserId=$(MYSQL_USER);Password=$(MYSQL_PASSWORD);"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_PRODUCTS_EXCHANGE
              value: products.exchange