apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"products-microservice"},"name":"products-microservice-deployment","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"products-microservice"}},"template":{"metadata":{"labels":{"app":"products-microservice"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_ENVIRONMENT","value":"Development"},{"name":"MYSQL_HOST","value":"mysql"},{"name":"MYSQL_PORT","value":"3306"},{"name":"MYSQL_DB","value":"ecommerceproductsdatabase"},{"name":"MYSQL_USER","value":"root"},{"name":"MYSQL_PASSWORD","value":"admin"},{"name":"RABBITMQ_HOST","value":"rabbitmq"},{"name":"RABBITMQ_USERNAME","value":"guest"},{"name":"RABBITMQ_PASSWORD","value":"guest"},{"name":"RABBITMQ_PORT","value":"5672"},{"name":"RABBITMQ_PRODUCTS_EXCHANGE","value":"products.exchange"}],"image":"microecommerceregistry.azurecr.io/products-microservice:22","name":"products-microservice","ports":[{"containerPort":7070}]}]}}}}
  creationTimestamp: "2025-05-07T06:44:13Z"
  generation: 4
  labels:
    app: products-microservice
  name: products-microservice-deployment
  namespace: dev
  resourceVersion: "2409870"
  uid: 9e7587a3-b89e-43f9-b6c3-8fda783aee76
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: products-microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-microservice
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: ecommerceproductsdatabase
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: admin
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_PRODUCTS_EXCHANGE
          value: products.exchange
        image: microecommerceregistry.azurecr.io/products-microservice:22
        imagePullPolicy: IfNotPresent
        name: products-microservice
        ports:
        - containerPort: 7070
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-05-07T06:44:13Z"
    lastUpdateTime: "2025-05-07T08:20:37Z"
    message: ReplicaSet "products-microservice-deployment-58696c567f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-07T08:20:38Z"
    lastUpdateTime: "2025-05-07T08:20:38Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
