apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"products-microservice"},"name":"products-microservice-deployment","namespace":"ecommerce-namespace"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"products-microservice"}},"template":{"metadata":{"labels":{"app":"products-microservice"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_ENVIRONMENT","value":"Development"},{"name":"MYSQL_HOST","value":"mysql"},{"name":"MYSQL_PORT","value":"3306"},{"name":"MYSQL_DB","value":"ecommerceproductsdatabase"},{"name":"MYSQL_USER","value":"root"},{"name":"MYSQL_PASSWORD","value":"admin"},{"name":"RABBITMQ_HOST","value":"rabbitmq"},{"name":"RABBITMQ_PORT","value":"5672"},{"name":"RABBITMQ_USERNAME","value":"guest"},{"name":"RABBITMQ_PASSWORD","value":"guest"},{"name":"RABBITMQ_PRODUCTS_EXCHANGE","value":"products.exchange"}],"image":"microecommerceregistry.azurecr.io/products-microservice:latest","name":"products-microservice","ports":[{"containerPort":7070}]}]}}}}
  creationTimestamp: "2025-05-02T00:18:40Z"
  generation: 3
  labels:
    app: products-microservice
  name: products-microservice-deployment
  namespace: ecommerce-namespace
  resourceVersion: "1617902"
  uid: e477fce4-758e-445c-8b04-ca2aa9b7b7c8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: products-microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-microservice
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: ecommerceproductsdatabase
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: admin
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_PRODUCTS_EXCHANGE
          value: products.exchange
        image: microecommerceregistry.azurecr.io/products-microservice:latest
        imagePullPolicy: Always
        name: products-microservice
        ports:
        - containerPort: 7070
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-02T00:18:40Z"
    lastUpdateTime: "2025-05-02T18:52:34Z"
    message: ReplicaSet "products-microservice-deployment-7489c66d44" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-05T00:49:55Z"
    lastUpdateTime: "2025-05-05T00:49:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
