apiVersion: v1
kind: Service
metadata:
  name: products-microservice
  namespace: dev
spec:
  selector:
    app: products-microservice
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
  type: ClusterIP