apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: staging
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: scottazurecontainerregistry.azurecr.io/ecommerce-mysql:latest
          envFrom:
            - secretRef:
                name: mysql-credentials