apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secret-manager
  namespace: dev
subjects:
- kind: ServiceAccount
  name: azdev-sa-f63cf5
  namespace: dev
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io